### ISSUE TITLE
Update for latest stdlib

### ISSUE THREAD

**Issue by lpil** [jrstrunk/tempo#6]
Hello!

The stdlib is undergoing a latest round of deprecations. There's a bunch of errors being emitted by this library, it would be fab to have them fixed!

Thank you,
Louis

**Comment by jrstrunk** [comment]
Hello! Wow there were a lot of them in this package. This should be fixed in v5.1.0. Thanks for the ping!

Also there is still a warning when compiling on JS about an unsafe int. I am working on another branch that reduces the base unit of time from nanoseconds to microseconds, which should resolve this.

**Comment by lpil** [comment]
Thank you 💜 

Is this OK to close now?

**Comment by jrstrunk** [comment]
Yes! Closing now
