### ISSUE TITLE
Using period to find the duration between datetimes gives a wrong answer

### ISSUE THREAD

**Issue by HSteffensen** [jrstrunk/tempo#7]
When I try to work with `duration` between `Datetime`s using `datetime.as_period`, the value is always wrong. I found that the number of days is wrong, in particular.

These test cases fail:

```gleam
import gleeunit
import gleeunit/should
import tempo/date
import tempo/datetime
import tempo/period

pub fn main() {
  gleeunit.main()
}

pub fn tempo_datetime_period_test() {
  let test_datetime = datetime.literal("2024-12-11T08:55:32.424420250Z")
  datetime.as_period(test_datetime, test_datetime)
  |> period.as_seconds
  |> should.equal(0)
}

pub fn tempo_date_period_test() {
  let test_date = date.literal("2024-12-11")
  date.as_period(test_date, test_date) |> period.as_days |> should.equal(0)
}
```

**Comment by jrstrunk** [comment]
Thank you for the report! 

When calculating the difference between days, it was not accounting for the fact that Jan of the next year is ahead of Dec of the current year, yet has a lower int representation. This issue only presented itself when comparing dates in December of the same year.

It should be fixed in release 5.1.1

I think I am going to deprecate `month.next` and `month.prior` and add a `month_year.prior` and `month_year.next`, so that users can only adjust months in the context of a year to hopefully avoid this mistake I made.

Cheers!
